//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BookDetail()
        {
            this.UserBookDetails = new HashSet<UserBookDetail>();
        }
    
        public int BookId { get; set; }
        public string BookName { get; set; }
        public string AuthorName { get; set; }
        public int RackNo { get; set; }
        public string C_Language { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string Rating { get; set; }
    
        public virtual Bookcategory Bookcategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserBookDetail> UserBookDetails { get; set; }
    }
}
