//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class eLibraryEntities : DbContext
    {
        public eLibraryEntities()
            : base("name=eLibraryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bookcategory> Bookcategories { get; set; }
        public virtual DbSet<BookDetail> BookDetails { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Subscription> Subscriptions { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<UserBookDetail> UserBookDetails { get; set; }
        public virtual DbSet<User> Users { get; set; }
    
        public virtual ObjectResult<sp_getAllSubscribedUser_Result> sp_getAllSubscribedUser()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getAllSubscribedUser_Result>("sp_getAllSubscribedUser");
        }
    
        public virtual ObjectResult<sp_getAllUsersWithBooks_Result> sp_getAllUsersWithBooks()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getAllUsersWithBooks_Result>("sp_getAllUsersWithBooks");
        }
    
        public virtual ObjectResult<sp_GetAllUsersBooks_Result> sp_GetAllUsersBooks()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetAllUsersBooks_Result>("sp_GetAllUsersBooks");
        }
    }
}
